// Regenerates src/data/auscultationSounds.js by reading the files actually present in
// public/assets/audio/auscultation. Every heart clip gets a periodicity score (q, 0 to 1)
// so the game can skip recordings too noisy to retime cleanly.
// Run after adding or removing clips: node src/scripts/genAusculManifest.mjs
//
// File names carry their own metadata, in one of two forms:
//   HLS-CMDS:  <SEX>_<TYPECODE>_<LOC>.wav        e.g. M_MSM_LUSB.wav, F_CC_LLA.wav
//   others:    <SRC>_<Type>_<LOC|any>_<n>.wav    e.g. CC_HolosystolicMurmur_A_0.wav
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readWav16, analyzeClip } from "../audio/retime.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../public/assets/audio/auscultation");

const HLS_HEART = { N: "Normal", LDM: "Late Diastolic Murmur", MSM: "Mid Systolic Murmur", LSM: "Late Systolic Murmur",
  ESM: "Early Systolic Murmur", AF: "Atrial Fibrillation", S3: "S3", S4: "S4", AVB: "AV Block", T: "Tachycardia" };
const HLS_LUNG = { N: "Normal", PR: "Pleural Rub", R: "Rhonchi", W: "Wheezing", FC: "Fine Crackles", CC: "Coarse Crackles" };
const SOURCES = { HF: "HF_Lung_V1", KA: "KAUH", CC: "CirCor", P16: "PhysioNet2016" };
// Type names written without spaces in file names, mapped back.
const unspace = (s) => s.replace(/([a-z])([A-Z])/g, "$1 $2");

function parse(name, hlsMap) {
  const base = name.replace(/\.wav$/i, "");
  const hls = base.match(/^([MF])_([A-Z0-9]+)_([A-Z]+)$/);
  if (hls && hlsMap[hls[2]]) return { type: hlsMap[hls[2]], loc: hls[3], src: "HLS-CMDS", sex: hls[1] };
  const other = base.match(/^([A-Za-z0-9]+)_([A-Za-z0-9]+)_([A-Za-z]+)_\d+$/);
  if (other && SOURCES[other[1]]) return { type: unspace(other[2]), loc: other[3], src: SOURCES[other[1]] };
  return null;
}

function build(sub, hlsMap, scoreIt) {
  const out = {};
  const skipped = [];
  for (const f of fs.readdirSync(path.join(root, sub)).sort()) {
    if (!f.endsWith(".wav")) continue;
    const m = parse(f, hlsMap);
    if (!m) { skipped.push(f); continue; }
    const entry = { id: f.replace(/\.wav$/, ""), loc: m.loc, src: m.src };
    if (m.sex) entry.sex = m.sex;
    if (scoreIt) {
      const b = fs.readFileSync(path.join(root, sub, f));
      const w = readWav16(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
      entry.q = +analyzeClip(w.x, w.fs, 0.3, 1.6).quality.toFixed(2);
    }
    (out[m.type] = out[m.type] || []).push(entry);
  }
  if (skipped.length) console.log(`  (skipped, name not understood: ${skipped.join(", ")})`);
  return out;
}

const heart = build("heart", HLS_HEART, true);
const lung = build("lung", HLS_LUNG, false);

const js = `// Auscultation recordings (public/assets/audio/auscultation). GENERATED by
// src/scripts/genAusculManifest.mjs from the file names; do not hand-edit.
// Sources, all credited on the credits screen (src/credits.js):
//   HLS-CMDS      Torabi, Shirani, Reilly, Mendeley 10.17632/8972jxbpmp.3 (CC BY 4.0)
//   HF_Lung_V1    Hsu et al., gitlab.com/techsupportHF/HF_Lung_V1 (CC BY 4.0)
//   KAUH          Fraiwan et al., Mendeley 10.17632/jwyy9np4gv.3 (CC BY 4.0)
//   CirCor        Oliveira et al., PhysioNet 10.13026/tshs-mw03 (ODC-By 1.0)
//   PhysioNet2016 Liu et al., PhysioNet challenge-2016 (ODC-By 1.0)
// All clips are mono 16-bit WAV at 4 kHz. Heart locations: RUSB aortic, LUSB pulmonic,
// LLSB tricuspid, A apex (mitral), RC / LC beside the sternum. Lung locations:
// R/L + U/M/L + A. "any" means the recording is not tied to one spot.
// q is how regularly periodic a heart clip is (0 to 1); low q clips are skipped.
export const AUSC_BASE = "/assets/audio/auscultation";
export const HEART_SOUNDS = ${JSON.stringify(heart, null, 1)};
export const LUNG_SOUNDS = ${JSON.stringify(lung, null, 1)};
`;
fs.writeFileSync(path.resolve(here, "../data/auscultationSounds.js"), js);
const line = (o) => Object.entries(o).map(([k, v]) => `${k} ${v.length}`).join(", ");
console.log("heart:", line(heart));
console.log("lung: ", line(lung));
